[workspace]
members = [
    "src/ultrustar",
    "src/webgl_gen_websys2gles",
    "src/websys2gles2",
    "xtask/checkit",
    "xtask/wasm",
]
default-members = [
    "src/ultrustar",
    "src/webgl_gen_websys2gles",
]
