[workspace]
members = [
    "src/gl_generator_websys",
    "src/ultrustar",
    "src/websys_gles2",
    "xtask/checkit",
    "xtask/wasm",
]
default-members = [
    "src/ultrustar",
    "src/gl_generator_websys",
]
