[package]
name = "ultrustar"
version = "0.1.0"
edition = "2021"

[lib]
name = "ultrastar_core"
crate-type = ["cdylib"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
  "console",
  "Document",
  "Element",
  "HtmlCanvasElement",
  "HtmlElement",
  "Node",
  "WebGlRenderingContext",
  "Window"
] }

[build-dependencies]
webgl_generator_websys = { path = "../webgl_generator_websys", version = "0.1.0" }
