[package]
name = "ultrustar"
version = "0.1.0"
edition = "2021"

[lib]
name = "ultrastar_core"
crate-type = ["cdylib"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
websys_gles2 = { path = "../websys_gles2", version = "0.1.0" }
js-sys = "0.3"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
  "Document",
  "Element",
  "HtmlCanvasElement",
  "HtmlElement",
  "Node",
  "Window"
]}
