name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    if: github.repository == 'suluke/ultrustar'

    steps:
    - uses: actions/checkout@v2
    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev libudev-dev libxcb-xfixes0-dev
    - name: Update to latest stable toolchain
      run: |
        rustup update
        rustup default stable
    - name: Install clippy + rustfmt
      run: rustup component add clippy rustfmt
    - name: Install wasm target
      run: rustup target install wasm32-unknown-unknown
    - name: Run checks
      run: cargo checkit

