name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update to latest stable toolchain
      run: rustup default stable
    - name: Install clippy + rustfmt
      run: rustup component add clippy rustfmt
    - name: Install wasm target
      run: rustup target install wasm32-unknown-unknown
    - name: Run checks
      run: cargo checkit

